package breakpoints;

public enum SetterError {
	ILLEGAL_CHIP,
	ILLEGAL_PLANE,
	ILLEGAL_BLOCK,
	ILLEGAL_PAGE,
	ILLEGAL_COUNT,
	ILLEGAL_PERCENT,
	ILLEGAL_WRITE_AMP,
	ILLEGAL_PARTITION,
	ILLEGAL_WRITE_LEVEL,
	ILLEGAL_WRITES_PER_ERASE,
	ILLEGAL_PARITY_OVERHEAD,
	ILLEGAL_LP, 
	ILLEGAL_STRIPE;
}
